### ISSUE TITLE
Expose React Component Function as Web Component Function

### ISSUE THREAD

**Issue by fabiofranzini** [ChristophP/web-react-components#33]
Is there a way to be able to map in addition to properties and events also functions to invoke?
**I have to expose the functions of the React Components as the functions of the Web Components**
Thank you!

**Comment by fabiofranzini** [comment]
Hi @ChristophP ,
I want to map React component's function to WebComponentfunction.
Example, if I have a React component with a function like "focus()", I'm not able to map "focus()" as a function in WebComponent.

**Comment by fabiofranzini** [comment]
Any news?

**Comment by etylsarin** [comment]
I'm looking for the same thing

**Comment by ChristophP** [comment]
Hi, sorry for the long inactivity and thanks for the explanation @fabiofranzini .
I see, you need to call function on the web component instance that delegate to the React component. I am planning a pass over this lib since it's been a while since the last release.
I will add that issue to the list of things I am planning to address. Can't really put a date on it right now but I am aiming for sometime in the remainder of 2019.
