### ISSUE TITLE
Typescript compatibility

### ISSUE THREAD

**Issue by d-molkentin** [ChristophP/web-react-components#37]
When I use the custom element like this:

`const customElement= document.createElement("my-element");`

With "register()" like this:

```
register(
    Element,
    "my-element",
    [
        "test",
    ],
);
```

Following code fails in Typescript

`customElement.test = "hello world!";`

Because it says that property "test" does not exist on HTMLELement.
Is there any way to fix this issue?

Thank you!

**Comment by ChristophP** [comment]
Hi @d-molkentin, sorry for the long delay. Is what you reported still an issue?
Since this library does provide any TS type definition it seems like you could fix the issue by fixing type definitions in your code. As far as I understand this library can not possibly know what properties you are going to attach. So I believe you would have to provide the correct type definition for that `customElement` yourself. Is that so?
I have never really used type script, so I don't know 100%.

**Comment by d-molkentin** [comment]
Hi ChristophP,
thanks for your answer anyway. I solved the issue exactly like you described by writing my own type and casting the element to it. I just thought if there could be an automatism.

**Comment by ChristophP** [comment]
@d-molkentin I am not of aware of a way to make this work in a way that works for everyone. But I am glad you got it working for you.
